config/routes.rb
Rails.application.routes.draw do

	devise_for :users 

	root :to => 'welcome#index'

	resources :products

	resources :offers

	get '/products', to: 'products#index', as: 'dashboard'

	resources :user

  
end

app/models/concerns/authenticateadmin.rb
module AuthenticateAdminHelper
	extend ActiveSupport::Concern

	def must_be_admin
		unless current_user && current_user.admin?
			redirect_to root_path, notice: "You're not admin, you do not have this privilages :(!"
			end
		end
end

app/models/offer.rb
class Offer < ActiveRecord::Base

	belongs_to :products

	validates :offername, presence: true
	validates :offerstartdate, presence: true
	validates :offerenddate, presence: true
	validates :offerdescription, presence: true 

	validate :offerstartdate_cannot_be_in_the_past
	validate :offerenddate_cannot_be_in_the_past

	
	#do not allow offerstartdate to be less than current date
	def offerstartdate_cannot_be_in_the_past
		errors.add(:offerstartdate, "Offer Start Date cannot be less than Todays date :( ! ") if offerstartdate < Date.today
	end

	#do not allow offerenddate to be less than current date
	def offerenddate_cannot_be_in_the_past
		errors.add(:offerenddate, "Offer Start Date cannot be less than Todays date :( ! ") if offerenddate < Date.today
	end

	
	#delete offers whose offerenddate are less than current date
	def self.deleteexpiredoffers
		@expiredoffers = Offer.where("offerenddate < ?", Date.today).ids
		Offer.destroy(@expiredoffers)
	end



end

app/models/product.rb
class Product < ActiveRecord::Base

	has_many :offers, :dependent => :destroy

	validates :name, presence: true
	validates :description, presence: true
	validates :image, presence: true
	validates :rate, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
	

	#paperclip
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/




end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         	:recoverable, :rememberable, :trackable, :validatable

	  def admin?
	    admin
	  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include ApplicationHelper


  before_action :configure_permitted_parameters, if: :devise_controller?


		def must_be_admin
			unless current_user && current_user.admin?
				redirect_to root_path, notice: "You're not admin, you do not have this privilages :(!"
			end
		end

  protected

	  def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) << :username
		devise_parameter_sanitizer.for(:account_update) << :username
	  end

end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

	before_action :must_be_admin, only: [:index, :new, :create, :edit, :update, :destroy] 

	def index
		@offers = Offer.all
		@products = Product.all
		
		#delete offers whose offerend date less than today
		Offer.deleteexpiredoffers
	end

	def show
	end
		
	def new 
		@offer = Offer.new
	end

	def create
	  	@offer = Offer.create(offer_params)

		if @offer.save
			flash[:notice] = 'Offer created'
			redirect_to @offer
		else
			flash[:notice] = 'Error, Please create offer again!'
			render 'new'
		end
	end

	def edit
		@offer = Offer.find(params[:id])
	end

	def update 
		@offer = Offer.find(params[:id])

		if @offer.update_attributes(offer_params)
			flash[:success] = "Offer updated :)!"
		        redirect_to @offer

		else
			render 'edit'
		end
	end

	def destroy
		@offer = Offer.find(params[:id])
		@offer.destroy
		flash[:success] = "Offer deleted successfully :)!"
		redirect_to offers_path
	end

	
	private
	
		def offer_params
			params.require(:offer).permit(:offername, :product_id, :offerstartdate, :offerenddate, :offerdescription)
		end



end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	before_action :must_be_admin, only: [:index, :new, :create, :edit, :update, :destroy]

	def index
		@users = User.where(admin: false)
		@products = Product.all
		@offers = Offer.all
	
	end


	def show
		
	end
		
	def new 
		@product = Product.new
	end

	def create
	  	@product = Product.create(product_params)

		if @product.save
			flash[:notice] = 'Product created'
			redirect_to @product
		else
			flash[:notice] = 'Error, Please create Product again!'
			render 'new'
		end
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update 
		@product = Product.find(params[:id])

		if @product.update_attributes(product_params)
			flash[:success] = "Product updated :)!"
		        redirect_to @product

		else
			render 'edit'
		end
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		flash[:success] = "Product deleted successfully :)!"
		redirect_to products_path
	end

	
	private
	
		def product_params
			params.require(:product).permit(:name, :description, :image, :rate)
		end
		

end

app/controllers/user_controller.rb
class UserController < ApplicationController
	
	before_action :must_be_admin, only: [:index, :edit, :destroy]

	def index
		@user = User.all
	end


	def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:success] = "User deleted successfully :)!"
		redirect_to products_path
	end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		
		if current_user.try(:admin?)
			flash[:notice] = 'Admin'
		end
	end

	def index 
		get_products
	end

	private
		def get_products
			@products = Product.all
		end	
end

app/helpers/application_helper.rb
module ApplicationHelper

	def check(pid, opid)
		if pid = opid
			@offer = @offers.where(product_id: pid)
			return true
		else
			return false
		end
	end

end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/offer_helper.rb
module OfferHelper
end

app/helpers/offers_helper.rb
module OffersHelper


end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Shoppee</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? && current_user.admin? %>
          <li><%= link_to "Dashboard", dashboard_path %></li>
          <li class="dropdown">
          	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Products <span class="caret"></span></a>
          	<ul class="dropdown-menu">
		    <li><li><%= link_to "Add Products", new_product_path %></li></li>
		    <li><li><%= link_to "All Products", products_path %></li></li>
          	</ul>
          </li>
          <li class="dropdown">
          	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Offers <span class="caret"></span></a>
          	<ul class="dropdown-menu">
		    <li><li><li><%= link_to "Add Offers", new_offer_path %></li></li></li>
		    <li><li><%= link_to "All Offers", offers_path %></li></li>
          	</ul>
          </li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% elsif user_signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>		
	<% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shoppee</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>
	
	<div class="container">
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>
		<%= render 'layouts/producterrors' %>

		<%= yield %>
	</div>

</body>
</html>

app/views/offers/_form.html.erb
<%= form_for @offer, :class => "form-horizontal" ,html: { multipart: true } do |f| %>
    <div class="form-group">
      <%= f.label :offername, :class => "control-label"  %>
      <div class="">
        <%= f.text_field :offername, :class => "form-control", :id => "offername" %>
      </div>
    </div>  

    <div class="form-group">
      <%= f.label :name, :class => "control-label"  %>
      <div class="">
	       <%= collection_select(:offer, :product_id, Product.all, :id, :name, {}, { :multiple => false } ) %>
      </div>
    </div> 	     

  <div class="form-group">
    <%= f.label :offerstartdate, :class => "control-label"  %>
    <div class="">
      <%= f.date_select  :offerstartdate, :start_year =>2016, required: true, :class => "form-control" %>
    </div>
  </div>  

    <div class="form-group">
      <%= f.label :offerenddate, :class => "control-label"  %>
      <div class="">
        <%= f.date_select  :offerenddate, required: true, :class => "form-control" %>
      </div>
    </div>      

    <div class="form-group">
      <%= f.label :offerdescription, :class => "control-label"  %>
      <div class="">
        <%= f.text_area :offerdescription, :class => "form-control", :id => "offerdescription" %>
      </div>
    </div>     

	<%= f.submit "Create", :class => "btn btn-primary" %>
<% end %>

app/views/offers/edit.html.erb
<h1> Edit Offer </h2>

<%= render 'form' %>

app/views/offers/index.html.erb
<h1>All Offers Page</h1>

<div class="row">
	<% @offers.each do |o|  %>
		<div class="col-lg-3" id="offers_index_page">
			<p> Offer Name - <b> <%= o.offername %> </b> </p>
			<p> Offer belongs to Product - <b> <%= o.product_id %> </b> </p>
			<p> Offer Start Date - <b> <%= o.offerstartdate %> </b> </b> </p>
			<p> Offer End Date - <b> <%= o.offerenddate %> </b> </p>
			<p> Offer Description - <b> <%= o.offerdescription %> </b> </p>		
			
			<%= link_to 'Edit', edit_offer_path(o), class: 'btn btn-primary btn-sm' %>
			<%= link_to 'Delete', o, method: :delete,
                                  data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
		</div>
	<% end %>
</div>

app/views/offers/new.html.erb
<div class="errors">
<% if @offer.errors.any? %>
	<div>
		Form has <%= pluralize(@offer.errors.count, "error") %>.
	</div>
	<ul>
		<% @offer.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>
</div>

<h1> Add New Offer </h2>

<%= render 'form' %>

app/views/offers/show.html.erb
<h4>Offer created successfully :) !</h4>

<%= link_to 'Return', offers_path %>

app/views/products/_form.html.erb
<%= form_for @product, :class => "form-horizontal" ,html: { multipart: true } do |f| %>
    <div class="form-group">
      <%= f.label :name, :class => "control-label"  %>
      <div class="">
        <%= f.text_field :name, :class => "form-control", :id => "name" %>
      </div>
    </div>  	

    <div class="form-group">
      <%= f.label :description, :class => "control-label"  %>
      <div class="">
        <%= f.text_area :description, :class => "form-control", :id => "description" %>
      </div>
    </div>      

    <div class="form-group">
      <%= f.label :image, :class => "control-label"  %>
      <div class="">
        <%= f.file_field  :image, :class => "form-control", :id => "image" %>
      </div>
    </div>  

    <div class="form-group">
      <%= f.label :rate, :class => "control-label"  %>
      <div class="">
        <%= f.text_field :rate, :class => "form-control", :id => "rate" %>
      </div>
    </div>          

	<%= f.submit "Create", :class => "btn btn-primary" %>
<% end %>

app/views/products/edit.html.erb
<h1> Edit Product </h2>

<%= render 'form' %>

app/views/products/index.html.erb
<h2>Welcome Admin :)</h2>


<div class="row">
	<div class="col-lg-12">
		<div class="tabbable" id="tabs-524748">
			<ul class="nav nav-tabs">
				<li class="active">
					<a href="#panel-197218" data-toggle="tab">Products</a>
				</li>
				<li>
					<a href="#panel-221290" data-toggle="tab">Users</a>
				</li>
			</ul>
			<div class="tab-content">
				<div class="tab-pane active" id="panel-197218">

				<% if @products.empty? %>
					<h3>Currently there are no items in the Store :( !</h4>
				<% end %>
					<% @products.each do |p|  %>
						<div class="row">
							<div class="col-lg-3">
								<%= image_tag p.image.url(:medium) %>
								<%= link_to 'Edit Product', edit_product_path(p), class: 'btn btn-primary btn-sm' %>
									<%= link_to 'Delete Product', p, method: :delete,
						                                  data: { confirm: "Product & related Offers will be deleted..You sure?" }, class: 'btn btn-danger btn-sm' %>								
							</div>
							<div class="col-lg-8">
								<h3> <%= p.name %> </h3>
								<b class="pull-right"> &#8377; <%= p.rate %> </b>	
								<p> - <%= p.description %> </p>

								<% if p.offers.empty? %>
									<p><i>Currently no Offers on this product :(</i></p>
								<% else %>
									<p>Available Offer(s): </p>
									<% p.offers.each do |po| %>								
										<div class="col-lg-12">									
											<p> <b><%= po.offername %></b> </p>
											<p><i> <%= po.offerdescription %> </i></p>
											<p>
												<span>Offer Starts On: <%= po.offerstartdate%> </span>
												<span>Offer Ends On: <%= po.offerenddate%> </span>
											</p>											
										</div>
									<% end %>					
								<% end %>
								</div>
							</div>
						<% end %>
					</div>

					<div class="tab-pane" id="panel-221290">

						<% if @users.empty? %>
							<h3>Currently no users have Registered to the Store :( !</h4>
						<% else %>
						<table class="table table-bordered">
							<thead>
								<tr>
									<th>
										Username
									</th>
									<th>
										Email
									</th>
									<th>
										
									</th>
								</tr>
							</thead>
							<tbody>
								<% @users.each do |u|  %>
								<tr>
									<td>
										<%= u.username %> 
									</td>
									<td>
										<%= u.email %> 
									</td>
									<td>
											<%= link_to 'Delete User', u, method: :delete,
							                                  data: { confirm: "You sure?" }, class: 'btn btn-danger' %>	
									</td>
								</tr>
								<% end %>
							</tbody>
						</table>
						<% end %>
					</div>
				</div>
			</div>		
	</div>
</div>

app/views/products/new.html.erb
<% if @product.errors.any? %>
	<div>
		Form has <%= pluralize(@product.errors.count, "error") %>.
	</div>
	<ul>
		<% @product.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

<h1> Add New Product </h2>

<%= render 'form' %>

app/views/products/show.html.erb
<h4>Offer created successfully :) !</h4>

<%= link_to 'Return', root_path %>

app/views/user/show.html.erb
<div class="row">
	<% @users.each do |u|  %>
		<%= u.username %> 
		<%= u.email %> 
		<%= link_to 'Edit User Details', edit_user_registration_path(u), class: 'btn btn-primary' %>
		<%= link_to 'Delete User', u, method: :delete,
                                  data: { confirm: "You sure?" }, class: 'btn btn-primary' %>	
	<% end %>
</div>

app/views/welcome/index.html.erb
<h1>Products</h1>

<% if @products.empty? %>
	<h3>Currently there are no items in the Store :( !</h4>
<% end %>


<div class="row" id="product_index_page">
<% @products.each do |p|  %>
	<div class="col-lg-3">
		<%= image_tag p.image.url(:medium) %>
		<h4> <%= p.name %> </h4>
		<b class="pull-right"> &#8377; <%= p.rate %> </b>		
		<p> <%= p.description %> </p>			
	</div>
<% end %>
</div>